# @Author: Jefferson Charlles
# @Date:   2021-10-07 04:31:24
# @Last Modified by:   Jefferson Charlles
# @Last Modified time: 2021-12-03 00:26:14
version: '3.9'

services:
    database: #ESSE É O NOME DO SERVICE QUE DEVE ESTAR NO ARQUIVO DE CRIAÇÃO DE CONEXÃO
        image: postgres
        container_name: database
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=docker
            - POSTGRES_PASSWORD=rentx
            - POSTGRES_DB=rentx
        volumes:
            - pgdata:/data/postgres

    redis:
        image: redis:alpine
        ports:
            - 6379:6379

    # app:
    #     build: .
    #     container_name: rentx
    #     restart: always
    #     ports:
    #         - 3333:3333
    #         - 9229:9229 #Você pode inserir essa porta tbm pra poder usar o debug
    #     volumes:
    #         - .:/usr/app
    #     links:
    #         - database
    #     depends_on:
    #         - database

volumes:
    pgdata:
        driver: local
